services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - twotier
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  next-app:
      image: rks007/nextjsupi
      container_name: next-app
      environment:
        - MONGO_URL=mongodb://mongo:27017/next #The reason for using mongodb://mongo:27017/next instead of mongodb://localhost:27017/next is that the mongo service is running in a different container. The hostname 'mongo' refers to the mongo service defined in this docker-compose file.
        - NEXTAUTH_SECRET=password_nextauth
        - NEXTAUTH_URL=http://localhost:3000
      ports:
        - "3000:3000"
      depends_on:
        - mongo
      networks:
        - twotier
      restart: always

networks:
  twotier:
    driver: bridge

volumes:
  mongo-data:




